### ISSUE TITLE
Literal real numbers incorrectly parsed as float instead of double

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/FAST-JAVA#124]
In Java, a floating-point literal such as '2.0' is treated as a `double`.

![image](https://github.com/moosetechnology/FAST-JAVA/assets/78592838/a5111ee1-b94d-4927-88f0-5869193fb5a1)

However, the parser will incorrectly interpret it as a `float` literal.

**Comment by NicolasAnquetil** [comment]
Replaced by #157
