### ISSUE TITLE
FASTJavaClassTypeExpression has 2 properties for name

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-JAVA#147]
- #name
- #typeName

I suggest to remove the second one

Note: see also #44 that could be related (deals with FASTJavaClassTypeExpression also)

**Comment by Gabriel-Darbord** [comment]
Duplicate of #50 where you suggested removing #name and I agreed because #typeName can be a FASTJavaTypeName but also a FASTJavaQualifiedTypeName.

**Comment by NicolasAnquetil** [comment]
well at least it shows that I am consistent :-)
