### ISSUE TITLE
FASTJavaTypeParameterExpression should have a single type

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/FAST-JAVA#155]
Currently, FASTJavaTypeParameterExpression can have multiple types.
However, a type parameter can only be bound to a single type.
In the present case, if there are multiple types, it'll output something like <X extends Foo, Bar> which declares two type parameters, X and Bar, instead of binding X to Foo and Bar.

_Originally posted by @Gabriel-Darbord in https://github.com/moosetechnology/FAST-JAVA/pull/154#discussion_r1375909140_

**Comment by NicolasAnquetil** [comment]
agreed

**Comment by Gabriel-Darbord** [comment]
In fact, it is possible to bind a type parameter to multiple types:
```Java
class MyClass<T extends A & B> { }
```
However, B (and subsequent types) **must** be an interface, but I'm not sure we want to represent that constraint.
