### ISSUE TITLE
baseline not charging Smacc-Java

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-JAVA#233]

**Comment by badetitou** [comment]
The readme says

```
Metacello new
  githubUser: 'moosetechnology' project: 'FAST-JAVA' commitish: 'v3' path: 'src';
  baseline: 'FASTJava';
  load: 'all'
```

Does it fails ?

Because tests relies on SmaCC so I am surprised

**Comment by NicolasAnquetil** [comment]
yes our mistake, the 'default' only load FAST-Java, not the importer (do we want to change that?)

But with monticello we can specify the 'smacc' group (of baselineOfFASTJava)
