### ISSUE TITLE
FASTJavaAssignmentExpression does not differentiate between simple or compound operators

### ISSUE THREAD

**Issue by RomainDeg** [moosetechnology/FAST-JAVA#26]
Currently there is no difference between two nodes `a = 0;` or `a += 0;`.
Maybe we should add an operator slot to keep that information in the node when parsing source code, or even have a different type of node for each type of assignment operator (feels a bit overkill in my opinion but that's an option).

**Comment by Gabriel-Darbord** [comment]
I agree with the slot which could contain the prefix, considering there are 11:
- +=
- -=
- *=
- /=
- %=
- &=
- |=
- ^=
- <<=
- \>>=
- \>>>=

**Comment by NicolasAnquetil** [comment]
yes definitely, we must know what is the exact operator.
A String property could do the trick

**Comment by NicolasAnquetil** [comment]
JavaInfixOperation (ie. binary operation) has a property #operator that contains a String

I propose to do the same here
