### ISSUE TITLE
FASTJavaCatchPartStatement should have a type slot

### ISSUE THREAD

**Issue by RomainDeg** [moosetechnology/FAST-JAVA#27]
Catch statements only keep in memory the body, parameter and try owner.
However, as the parameter is a FASTJavaVariableExpression, it does not hold information on the type of the variable.

As catch statements can only have one variable, maybe simply adding a type slot (like FASTJavaVarDeclStatement for example) would do the trick.

**Comment by Gabriel-Darbord** [comment]
I think we are also missing the capacity to express multi-catches.
```java
try {...} catch(Exception | Error caught) {...}
```

**Comment by NicolasAnquetil** [comment]
when in doubt go back to the grammar:
```
CatchClause:  
    catch ( {VariableModifier} CatchType Identifier ) Block

CatchType:
    QualifiedIdentifier { | QualifiedIdentifier }
```
so I would say we need an identifier + a collection of types

**Comment by Gabriel-Darbord** [comment]
@NicolasAnquetil where do you find this grammar?
I've been looking [here](https://www.ibm.com/docs/api/v1/content/SS5JSH_9.5.0/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/CatchClause.html) but it doesn't seem as complete.
