### ISSUE TITLE
FASTJavaNewArray cannot represent multi-dimensional arrays of unspecified size

### ISSUE THREAD

**Issue by RomainDeg** [moosetechnology/FAST-JAVA#30]
When an array initializer specifies the size of each dimension :

![image](https://github.com/moosetechnology/FAST-JAVA/assets/98580879/8a340810-7b8e-4946-8340-c41bedf8db3e)

And when it does not :

![image](https://github.com/moosetechnology/FAST-JAVA/assets/98580879/3efa64e7-b515-4813-ae41-8e82ab0b3434)

As you can see, when the size is specified, a `FASTJavaIntegerLiteral` is added to the `arguments` field of the node and therefore the information is kept after parsing.
However, if the size are not specified, there is no way (unless we infer it from the children nodes? doesn't sound like a good idea) to know how many dimensions this array has.

Most other array nodes (like accesses, or type expression) are built recursively in order to represent multi-dimensionality, so maybe the same logic could be applied for initializers?

**Comment by NicolasAnquetil** [comment]
Not sure I get the problem

AST represents what there is in the source code, not what the source code does.
If there is no size specified in the array declaration, then there should not be any in the AST either (but there should be a node to describe the initialization part).

**Comment by RomainDeg** [comment]
I think these examples might be easier to understand :

![image](https://github.com/moosetechnology/FAST-JAVA/assets/98580879/654a6e19-10ea-4f9f-847d-1cdbe65fdbc3)

The issue is that if the sizes are not specified (and therefore not present in the AST, so far no problem) then there is no way for us to know how many dimensions our array has (is it `String[]`, or `String[][]` ?).

**Comment by Gabriel-Darbord** [comment]
> Most other array nodes (like accesses, or type expression) are built recursively in order to represent multi-dimensionality, so maybe the same logic could be applied for initializers?

While this is not the most efficient in space, nesting has indeed been the way to go so far.

**Comment by NicolasAnquetil** [comment]
The problem of nesting is that it is not a recursive construct:
- when you have an ArrayAccess with 2 dimensions you can represent it as an ArrayAcces (1 dimension) inside ana array access (1 dimension)
- but a newArray with 2 dimensions is not a newArray of 1 dimension containing a newArray

In the end I propose to represent it as as it is now, but with a new FASTJavaEmptyDimExpression to mark empty arguments
